---
driver:
  name: docker
  privileged: true

---
platforms:
- name: ubuntu-14.04
  driver_config:
    image: ubuntu:14.04
    platform: ubuntu
- name: ubuntu-16.04
  driver_config:
    image: ubuntu:16.04
    platform: ubuntu
- name: centos-6.4
  driver_config:
    image: centos:6.4
    platform: centos
- name: centos-7.2
  driver_config:
    image: centos:7.2
    platform: centos